---
linters:
  enable-all: true
  disable:
    - deadcode          # deprecated
    - depguard          # annoying - must maintain a constant whitelist of import-able packages
    - exhaustruct       # annoying - forces full struct initializations
    - exhaustivestruct  # annoying - forces full struct initializations
    - godot             # annoying - ending all comments with periods
    - goerr113          # annoying - no dynamic errors, forces named errors or wrapping errors - annoying
    - golint            # replaced by stylecheck
    - gomnd             # annoying - magic numbers more annoying to alert on than deal with
    - ifshort           # deprecated
    - interfacer        # deprecated
    - maligned          # deprecated
    - nosnakecase       # deprecated
    - scopelint         # deprecated
    - structcheck       # deprecated
    - tagliatelle       # annoying - enforces "no snake case" in JSON tags on things we don't control
    - varcheck          # deprecated
      # - revive
      # - stylecheck
linters-settings:
  forbidigo:
    forbid:
      - ^print.*$
  dupl:
    threshold: 1000
  lll:
    line-length: 150
  nlreturn:
    block-size: 2
  gosec:
    config:
      G302: "0644"
      G306: "0644"
