---
name: 'DefectDojo-Inc Lint'
description: 'Run linters with standardized configuration'
author: 'cneill'
inputs:
  go-version:
    description: 'The version of Go to set up for linting with golangci-lint'
    default: '1.22'
    required: false
  custom-config:
    desciption: 'Set this to true if you want to lint your repo with the .golangci.yml file in your repository'
    default: false
    required: false
  timeout:
    description: 'Modify this if the linter is taking longer than the default timeout of 1m0s. Should be a Go duration'
    default: '1m0s'
    required: false
runs:
  using: "composite"
  steps:
    - name: Check out target repo
      uses: actions/checkout@v4

    - name: Check out action-lint repo
      run: git clone https://github.com/DefectDojo-Inc/lint-action.git ${{ github.workspace }}/lint-action
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ inputs.go-version }}'

    - name: Run golangci-lint (global config)
      uses: golangci/golangci-lint-action@v6  # TODO: replace with commit hash?
      if: ${{ inputs.custom-config == 'false' }}
      with:
        args: "--config ${{ github.workspace }}/lint-action/.golangci.yml --go ${{ inputs.go-version }} --timeout ${{ inputs.timeout }}"
        version: latest  # TODO: replace with commit hash?

    - name: Run golangci-lint (repo config)
      uses: golangci/golangci-lint-action@v6  # TODO: replace with commit hash?
      if: ${{ inputs.custom-config == 'true' }}
      with:
        args: "--go ${{ inputs.go-version }} --timeout ${{ inputs.timeout }}"
        version: latest  # TODO: replace with commit hash?
